### ISSUE TITLE
App doesn't run in a case-sensitive filesystem

### ISSUE THREAD

**Issue by tewson** [giacomorebonato/a11y-tips-for-web#1]
In a case-sensitive filesystem like Linux, running `npm start` results in a `Module not found` error. This is because `presentation.tsx` is trying to import `./slides/intro` while the actual filename is `Intro.tsx` (uppercase I). ;)

**Comment by giacomorebonato** [comment]
Thanks, I didn't notice!

**Comment by giacomorebonato** [comment]
Fixed :)
